const express=require('express')
const verifyAuthToken=require('../middlewares/auth')
const upload=require('../middlewares/multerUpload')
const router=express.Router()
const { createPost, getBlogs, getBlog, updateBlog, deleteBlog, updateCover, likePost, commentPost, getComments } = require('../controllers/blogController')
router.post("/",verifyAuthToken,upload.single("coverImage"),createPost)
router.get("/",getBlogs)
router.get("/:id",getBlog)
router.put("/:id",verifyAuthToken,updateBlog)
router.delete("/:id",verifyAuthToken,deleteBlog)
router.patch("/coverImage/:id",verifyAuthToken,upload.single("coverImage"),updateCover)
router.get("/:id/like",verifyAuthToken,likePost)
router.post("/:id/comment",verifyAuthToken,commentPost)
router.get("/:id/comments",getComments)
module.exports=router